experimental = ["setup-scripts"]
nextest-version = "0.9.98"

[scripts.setup.fixture_repo]
command = "tests/scripts/nextest/setup-fixture.sh"

[[profile.default.scripts]]
filter = "all()"
setup = "fixture_repo"
