#!/usr/bin/env bash
set -euo pipefail

ROOT=${1:-$(pwd)}
CYC_DIR="$ROOT/.agents/cycles"
OVERLAY="$ROOT/.agents/repo_overlay.json"

if [[ ! -d "$CYC_DIR" ]]; then
  echo "[cycle check] Missing .agents/cycles directory." >&2
  echo "Run: just new-cycle \"short description\"" >&2
  exit 1
fi

shopt -s nullglob
files=($CYC_DIR/*.md)
shopt -u nullglob

if [[ ${#files[@]} -eq 0 ]]; then
  echo "[cycle check] No cycle files found in .agents/cycles." >&2
  echo "Run: just new-cycle \"short description\"" >&2
  exit 1
fi

latest=$(ls -1 "$CYC_DIR"/*.md | sort | tail -n1)

# Prefer GNU grep (ggrep) if available; fallback to grep
GREP=$(command -v ggrep || command -v grep)

# Simple content checks (fixed strings for portability)
if ! "$GREP" -q -F "# Cycle " "$latest"; then
  echo "[cycle check] Latest cycle file lacks a '# Cycle' header: $latest" >&2
  exit 1
fi

if ! "$GREP" -q -F "1) Summary" "$latest"; then
  echo "[cycle check] Latest cycle file missing '1) Summary' section: $latest" >&2
  exit 1
fi

if ! "$GREP" -q -F "5) Orchestration Plan" "$latest"; then
  echo "[cycle check] Latest cycle file missing '5) Orchestration Plan' section: $latest" >&2
  exit 1
fi

if [[ ! -f "$OVERLAY" ]]; then
  echo "[cycle check] Missing overlay JSON: $OVERLAY" >&2
  echo "It should be generated by 'just new-cycle'." >&2
  exit 1
fi

echo "[cycle check] OK — found $latest and overlay JSON." >&2
